// apps/web/src/components/scroll-to-top.tsx
"use client";

import { ChevronUp } from "lucide-react";
import { useEffect, useState } from "react";

export function ScrollToTop() {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const toggleVisibility = () => {
      if (window.scrollY > 400) {
        setIsVisible(true);
      } else {
        setIsVisible(false);
      }
    };

    window.addEventListener("scroll", toggleVisibility);
    return () => window.removeEventListener("scroll", toggleVisibility);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  return (
    <button
      onClick={scrollToTop}
      aria-label="Scroll to top"
      className={`group fixed bottom-6 right-6 z-[90] flex h-10 w-10 items-center justify-center border border-border bg-background/80 text-foreground/70 backdrop-blur-md transition-all duration-300 hover:border-primary hover:text-primary md:bottom-8 md:right-8 ${
        isVisible
          ? "translate-y-0 opacity-100"
          : "pointer-events-none translate-y-10 opacity-0"
      }`}
    >
      <ChevronUp className="h-4 w-4" />
      {/* Optional gaming corner trace */}
      <span className="absolute -right-[1px] -top-[1px] h-2 w-2 border-r border-t border-primary opacity-0 transition-opacity duration-300 group-hover:opacity-100" />
      <span className="absolute -bottom-[1px] -left-[1px] h-2 w-2 border-b border-l border-primary opacity-0 transition-opacity duration-300 group-hover:opacity-100" />
    </button>
  );
}

// apps/web/src/lib/components/ScrollToTop.svelte
<script lang="ts">
	import { IconArrowUp } from '@tabler/icons-svelte-runes';
	import * as m from '#lib/paraglide/messages.js';

	let visible = $state(false);

	$effect(() => {
		const handleScroll = () => {
			visible = window.scrollY > 350;
		};

		window.addEventListener('scroll', handleScroll, { passive: true });
		handleScroll();

		return () => {
			window.removeEventListener('scroll', handleScroll);
		};
	});

	function scrollToTop() {
		window.scrollTo({
			top: 0,
			behavior: 'smooth'
		});
	}
</script>

<div
	class="fixed right-6 bottom-6 z-50 transition-all duration-300 {visible
		? 'pointer-events-auto translate-y-0 opacity-100'
		: 'pointer-events-none translate-y-4 opacity-0'}"
>
	<button
		type="button"
		onclick={scrollToTop}
		class="group flex h-11 w-11 items-center justify-center rounded-full border border-border/80 bg-card/85 text-foreground shadow-lg backdrop-blur-md transition-all duration-200 hover:-translate-y-1 hover:border-primary/60 hover:bg-primary hover:text-primary-foreground hover:shadow-primary/20"
		aria-label={m.scroll_to_top()}
		title={m.scroll_to_top()}
	>
		<IconArrowUp
			size={18}
			stroke={2.5}
			class="transition-transform duration-200 group-hover:-translate-y-0.5"
		/>
	</button>
</div>
